name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.6
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-solved
          verbose: true
          commit-header: '[LeetCode Sync]'